/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
import processing.video.*;
import ddf.minim.*;

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:511028:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
  loadVideo(-1);

} //_CODE_:panel1:511028:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:223450:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
  panel1.setCollapsed(true);
  loadVideo(0);
} //_CODE_:imgButton1:223450:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:604619:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
    panel1.setCollapsed(true);
    loadVideo(1);

} //_CODE_:imgButton2:604619:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:286126:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
    panel1.setCollapsed(true);
    loadVideo(2);

} //_CODE_:imgButton3:286126:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  panel1 = new GPanel(this, 7, 7, 465, 264, "Choisissez votre video");
  panel1.setText("Choisissez votre video");
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  imgButton1 = new GImageButton(this, 160, 98, 100, 60, new String[] { "data/image_button/img1.tga", "data/image_button/img1.tga", "data/image_button/img1.tga" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 321, 96, 100, 60, new String[] { "data/image_button/img1.tga", "data/image_button/img1.tga", "data/image_button/img1.tga" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 10, 98, 100, 60, new String[] { "data/image_button/img1.tga", "data/image_button/img1.tga", "data/image_button/img1.tga" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  label1 = new GLabel(this, 17, 170, 80, 20);
  label1.setText("Kata");
  label1.setOpaque(false);
  label2 = new GLabel(this, 165, 171, 80, 20);
  label2.setText("Off");
  label2.setOpaque(false);
  label3 = new GLabel(this, 331, 166, 80, 20);
  label3.setText("Armed");
  label3.setOpaque(false);
  panel1.addControl(imgButton1);
  panel1.addControl(imgButton2);
  panel1.addControl(imgButton3);
  panel1.addControl(label1);
  panel1.addControl(label2);
  panel1.addControl(label3);
}

// Variable declarations 
// autogenerated do not edit
GPanel panel1; 
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
