/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:415012:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:415012:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:399829:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:399829:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:793431:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton3:793431:

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:window1:842617:
  appc.background(230);
} //_CODE_:window1:842617:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  imgButton1 = new GImageButton(this, 24, 134, 100, 60, new String[] { "", "", "" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 158, 134, 100, 60, new String[] { "", "", "" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 296, 135, 100, 60, new String[] { "", "", "" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  label1 = new GLabel(this, 97, 25, 205, 17);
  label1.setText("Choisissez votre video");
  label1.setOpaque(false);
  Cut = new GLabel(this, 30, 208, 80, 20);
  Cut.setText("Cut");
  Cut.setOpaque(false);
  label2 = new GLabel(this, 167, 208, 80, 20);
  label2.setText("Kick");
  label2.setOpaque(false);
  label3 = new GLabel(this, 306, 208, 80, 20);
  label3.setText("Fun");
  label3.setOpaque(false);
  window1 = new GWindow(this, "Window title", 0, 0, 240, 120, false, JAVA2D);
  window1.addDrawHandler(this, "win_draw1");
}

// Variable declarations 
// autogenerated do not edit
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
GLabel label1; 
GLabel Cut; 
GLabel label2; 
GLabel label3; 
GWindow window1;

